site:
  url: "http://127.0.0.1:8000"
  title: "snow's blog"
  language: "zh"
  logo: "https://s.libforest.com/images/header/header-logo.png"
  logo_name: "楓"

mode.publish:
  site:
    url: "https://example.com"

languages.en:
  sections:
    _index:
      paginate: 2
      filter:
        type: "posts,markdown"
  translations: ""

sections:
  _index:
    paginate: 2
    filter:
      type: "posts,markdown"
      # tags: "post3"
  _default:
    orderby: "date desc"
    templates: "posts.html"
    page_template: "page.html"
  posts:
    page_template: "post.html"
  pages:
    path: ""

taxonomies:
  _default:
    feed_path: "{taxonomy}/{slug}/index.xml"
    feed_template: ""
  categories:
    lang: "zh"
    path: "categories/index.html"
    template: "categories/list.html"
    term_path: "categories/{slug}/index.html"
    term_template: "categories/single.html"
  tags:
    weight: -1
  authors:
  date:2006/01:
    path: "archives/index.html"
    template: "archives.html"
    term_path: "archives/{slug}/index.html"
    term_template: "period_archives.html"
    feed_path: ""

output_dir: "output"
content_dir: "content"

# page_dirs:
#   - "markdown"
page_paginate: 3

# static_exts:
#   - ".js"
#   - ".css"
# static_dirs:
# - "static/robots.txt"
# - "static/favicon.ico"
# - "static/CNAME"
# - "static/css/"
static_paths:
  # static: "/"
  # "static/css/main.css": "static/css/"
  "@theme/static": "static/"

hooks:
  - "encrypt"
  - "shortcode"

theme:
  # name: "archie-snow"
  name: "snow"
  # override: "layouts"

params:
  extra:
    links:
      - name: "友链"
        url: "/pages/friends.html"
      - name: "联系"
        url: "/pages/contact.html"
      - name: "项目"
        url: "/pages/project.html"
      - name: "时间轴"
        url: "/pages/timeline.html"
    social:
      - name: "Github"
        icon: "github"
        url: "https://github.com/honmaple/archie-snow"
      - name: "Twitter"
        icon: "twitter"
        url: "https://github.com/honmaple/archie-snow"
      - name: "Gitlab"
        icon: "gitlab"
        url: "https://github.com/honmaple/archie-snow"
    menus:
      - name: "文章归档"
        url: "/archives/index.html"
        submenu:
          - name: "标签"
            url: "/tags/index.html"
          - name: "分类"
            url: "/categories/index.html"
          - name: "作者"
            url: "/authors/index.html"
      - name: "关于"
        url: "/about"
    mode: "toggle"
    copyright: "honmaple"
  assets:
    css:
      files:
        - "@theme/static/scss/main.scss"
        - "@theme/static/scss/entry.scss"
      filters:
        - libscss:
            path: ["@theme/static/scss/"]
        - cssmin:
      output: "static/lib.min.css"
      retain: true
