site:
  url: "http://127.0.0.1:8000"
  title: "snow"
  language: "zh"

mode.publish:
  site:
    url: "https://honmaple.me"
  languages.en:
    site.url: "http://honmaple.me/en"

# languages.en:
#   site:
#     url: "http://127.0.0.1:8000/en"
#   output_dir: "output/en"

sections:
  _default:
    path: ""
    templates: "posts.html"
    page_template: "page.html"
  posts:
    path: "posts/index.html"
    paginate_filter: ""
    page_path: "articles/{date:%Y}/{date:%m}/{slug}.html"
    # page_template: "post.html"
  pages:
    path: ""
    page_path: "pages/{slug}.html"
    hidden: true
  drafts:
    draft: true

taxonomies:
  tags:
    template: "tags/list.html"
    term_template: "tags/single.html"
  authors:
    template: "tags/list.html"
    term_template: "tags/single.html"

output_dir: "output"
content_dir: "content"

build_filter: "not draft"
build_ignore_files: "not draft"

statics:
  static:
    path: "assets"

theme:
  # name: "archie-snow"
  # name: "snow"
  # override: "layouts"

registered_hooks:
  - "pelican"
  - "i18n"
  - "assets"
  - "encrypt"
  - "shortcode"
  - "sofile"
hooks:
  internal:
    converter:
      tags: "^aaaaa"
      categories: ""
  sofiles:
    files:
      - "sofile.so"
  encrypt:
    password: "123456"

params.extra:
  menus:
    - name: "Home"
      url: "/"
    - name: "All Posts"
      url: "/posts"
    - name: "About"
      url: "/pages/about.html"
    - name: "Tags"
      url: "/tags"
  mode: "toggle"
  copyright: "honmaple"
