site:
  url: "http://127.0.0.1:8000"
  title: "snow's blog"
  language: "zh"

mode.publish:
  site:
    url: "https://example.com"

sections:
  _index:
    paginate: 2
    filter:
      type: "posts"
      # tags: "post3"
  _default:
    orderby: "date desc"
    templates: "posts.html"
    page_template: "page.html"
  pages:
    path: ""

taxonomies:
  _default:
    feed_path: "{taxonomy}/{slug}/index.xml"
    feed_template: ""
  categories:
    lang: "zh"
    path: "categories/index.html"
    template: "categories/list.html"
    term_path: "categories/{slug}/index.html"
    term_template: "categories/single.html"
  tags:
    weight: -1
  authors:
  date:2006/01:
    path: "archives/index.html"
    template: "archives.html"
    term_path: "archives/{slug}/index.html"
    term_template: "archives.html"

output_dir: "output"
content_dir: "content"

# page_dirs:
#   - "markdown"
page_paginate: 3

# static_exts:
#   - ".js"
#   - ".css"
# static_dirs:
# - "static/robots.txt"
# - "static/favicon.ico"
# - "static/CNAME"
# - "static/css/"
static_paths:
  # static: "/"
  # "static/css/main.css": "static/css/"
  "@theme/static": "static/"

hooks:
  - "encrypt"
  - "shortcode"

theme:
  name: "archie-snow"
  # override: "layouts"

params:
  extra:
    social:
      - name: "Github"
        icon: "github"
        url: "https://github.com/honmaple/archie-snow"
      - name: "Twitter"
        icon: "twitter"
        url: "https://github.com/honmaple/archie-snow"
      - name: "Gitlab"
        icon: "gitlab"
        url: "https://github.com/honmaple/archie-snow"
    menus:
      - name: "Home"
        url: "/"
      - name: "All post"
        url: "/posts/index.html"
      - name: "About"
        url: "/about"
      - name: "Tags"
        url: "/tags/index.html"
    mode: "toggle"
    copyright: "honmaple"
  assets:
    css:
      files:
        - "@theme/static/scss/main.scss"
        - "@theme/static/scss/entry.scss"
      filters:
        - libscss:
            path: ["@theme/static/scss/"]
        - cssmin:
      output: "static/lib.min.css"
      retain: true
