site:
  url: "http://127.0.0.1:8000"
  title: "snow's blog"
  language: "zh"

mode.publish:
  site:
    url: ""
  page_filter: "-drafts"
  page_meta:
    drafts:
      output: ""

content_dir: "content"
output_dir: "output"

# page_dirs:
#   - "content"
page_meta:
  drafts:
    lookup:
      - "post.html"
  pages:
    lookup:
      - "post.html"
    output: "pages/{filename}.html"
page_paginate: 3

static_url: "{path}"
static_exts:
  - ".js"
  - ".css"
# static_dirs:
# - "static/robots.txt"
# - "static/favicon.ico"
# - "static/CNAME"
# - "static/css/"
static_meta:
  # static: "/"
  # "static/css/main.css": "static/css/"
  theme/static: "static/"

hooks:
  - "feed"

theme:
  path: "simple"
  engine: "pongo2"
  override: "layouts"

params:
  feed:
    limit: 10
  webassets:
    css:
      files:
        - "theme/static/scss/main.scss"
        - "theme/static/scss/entry.scss"
      filters:
        - libscss:
            path: ["theme/static/scss/"]
        - cssmin:
      output: "static/lib.min.css"
