lang = "en"
locale = "en"
timezone = "Asia/Shanghai"
author = "honmaple"
output = "etc/output"
orderby = ["date"]

dir = "etc/content"
pagedir = []
articledir = ["org"]

[log]
level = "debug"
timestamp = false

[site]
url = "http://127.0.0.1:8000"
title = "honmaple's blog"
subtitle = "风落花语风落天，花落风雨花落田."

[publish]
url = "https://honmaple.me"

[[static]]
file = "extra/robots.txt"
save_path = "robots.txt"

[theme]
include = "etc/theme.toml"

[plugin]
include = "etc/plugin.toml"

[feed]
title = "{title}"
limit = 10
format = "rss"
save_path = "feeds/atom.xml"

[feed.tag]
title = "{slug} - {title}"
save_path = ""

[feed.author]
title = "{slug} - {title}"
save_path = ""

[feed.category]
title = "{slug} - {title}"
format = "rss"
save_path = "feeds/{slug}.atom.xml"
